---
- name: launch docker compose install
  template:
    src: docker-compose.yml.j2
    dest: /tmp/docker-compose.yml

- block:
    - name: Launch docker compose file
      shell: docker-compose -f docker-compose.yml up -d
      args: 
        chdir: /tmp/
      register: setup_docker_compose
    
  rescue:
    - name: debug docker compose launch
      debug:
        msg: "{{ setup_docker_compose }}"

  