---
- name: Provision an EC2 Instance
  hosts: localhost
  vars_files:
    - aws_secret.yml
  gather_facts: false
  tasks:
    - name: Launch a new EC2 instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "ec2-nc1-test"
        instance_type: t2.micro
        image_id: ami-01103fb68b3569475
        count: 1
        region: us-east-2
        network:
          assign_public_ip: true
      register: ec2
