- name: Installation and configuration of a nextcloud instance
  hosts: testvm
  vars_files:
     - secret.yml
  vars:
    - dir_nextcloud: /var/www/nextcloud
    - db_type: mysql
    - db_name: nextcloud
    - nc_admin: nc_adm
    - mail_addr: mehdibennouar@protonmail.com
    - nc_config:
        - { key: 'trusted_domains', value: '*'}

  pre_tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: 'yes'
        
    - name: Install docker compose and sudo
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - docker-compose
        - sudo
        - php

  roles:
    - docker_deploy

  tasks:
    - name: Create nextcloud directory
      file:
        path: "{{ dir_nextcloud }}"
        state: directory

    - name: Change folder's permissions
      file:
        path: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0744'
        recurse: yes

    # - name: Debug php occ 
    #   command: /var/www/html/occ
    #   register: try_occ

    # - name: debug it
    #   debug:
    #     msg: "{{ try_occ }}"

    - name: Complete nextcloud's installation
      template:
        src: nc_install.sh.j2
        dest: /tmp/nc_install.sh

    - name: change file permissions
      file:
        path: /tmp/nc_install.sh
        owner: root
        group: root
        mode: '0744'

    # - name: launch nextcloud script
    #   command: >
    #     ./nc_install.sh
    #   args:
    #     chdir: /tmp/
          
          
    - name: Complete nextcloud's installation
      command: >
        docker exec -u www-data app_nc php /var/www/html maintenance:install \
        --data-dir "{{ dir_nextcloud }}/files/" \
        --database "{{ db_type }}" \
        --database-name "{{ db_name }}" \
        --database-user "{{ mysql_user }}" \
        --database-pass "{{ mysql_pwd }}" \
        --admin-user "{{ nc_admin }}" \
        --admin-pass "{{ nc_passwd }}" \
        --admin-email "{{ mail_addr }}" \
        /
      args:
          creates: /var/www/nextcloud/config/config.php
      register: setup_nc
      notify: Restart Apache

    - name: Add trusted domains
      command: >
        docker exec -u www-data app_nc php /var/www/html config:system:set trusted_domains 2 --value="{{ item.value }}"
      loop: "{{nc_config}}"

    - name: Disable some applications
      command: >
        docker exec -u www-data app_nc php /var/www/html app:disable {{ item }}
      with_items:
      - dashboard
        - circles
        - weather_status
        - activity
        - photos
        - recommendations
        - firstrunwizard
        - nextcloud_announcements
        - contactsinteraction

    - name: Customization of the nextcloud instance
      command: >
        docker exec -u www-data app_nc php /var/www/html theming:config {{ item }}
      with_items:
        - { key: 'color', value: "#808000"}
        - { key: 'name', value: "KanzDrive"}
        - { key: 'url', value: "https://www.kanzdrive.com"}
        - { key: 'slogan', value: "Your own secure and fast cloud storage service."}

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
