- name: Installation and configuration of a nextcloud instance
  hosts: localhost
  vars_files:
    - secret.yml
  vars:
    - dir_nextcloud: /var/www/nextcloud
    - db_type: mysql
    - db_name: nextcloud
    - 
  roles:
    - docker_deploy

  tasks:
    - name: Create nextcloud directory
      file:
        path: "{{ dir_nextcloud }}"
        state: directory

    - name: Configure the nextcloud fresh install
      shell: >
    php /var/www/html/occ maintenance:install
    --data-dir "{{ dir_nextcloud }}/files/"
    --database "{{ db_type }}"
    --database-name "{{ db_name }}"
    --database-user "{{ mysql_user }}"
    --database-pass "{{ mysql_pwd }}"
    --admin-user "{{ nc_admin }}"
    --admin-pass "{{ nc_passwd }}"
    --admin-email "{{ mail_addr }}"
  args:
      creates: /var/www/nextcloud/config/config.php