---
- name: launch docker compose install
  template:
    src: docker-compose.yml.j2
    dest: /tmp/docker-compose.yml

- name: Launch docker compose file
  shell: docker-compose up -d
  args: 
    chdir: /tmp/