---

- name: install php packages
  apt:
    name: "{{ php_packages }}"
    state: latest

- name: install other packages
  apt:
    name: "{{ packages }}"
    state: latest

- name: change php.ini memory settings
  lineinfile:
    path: "/etc/php/{{ php_version }}/fpm/php.ini"
    line: "memory_limit = 512M"
    regexp: "^memory_limit ="
    backrefs: yes

- name: Ensure services are enabled and running
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ services }}"

- name: add .my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_passwd }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL,GRANT'
    host: "{{ item }}"
    check_implicit_admin: true
    state: present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  become: yes

- name: remove default apache configuration file
  file:
    path: /var/www/html/index.html
    state: absent
  notify: Reload apache
