version: '3'

services:
  nginx_rp:
    container_name: nginx_rp
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /.certs:/etc/nginx/certs
    networks:
      - proxy
      
networks:
  proxy:
    driver: bridge