instance_ip: "167.172.72.220"

dir_nextcloud: /var/www/nextcloud
db_type: mysql
db_name: nextcloud
nc_admin: nc_adm
mail_addr: mehdibennouar@protonmail.com

mysql_name: nextcloud

port_app: 8080

db_container_name: db_nc
container_name: app_nc

nc_url: "KanzDrive.ca"

trusted_domains:
  - "{{ nc_url }}"
  - "localhost"

ip_nc: 167.172.72.220
