instance_ip: "143.198.130.2"

dir_nextcloud: /var/www/nextcloud
db_type: mysql
db_name: nextcloud
nc_admin: nc_adm
mail_addr: mehdibennouar@protonmail.com

nc_url: localhost

trusted_domains:
  - "{{ nc_url }}"
  - "localhost"