---

- name: Testing the docker compose template file
  hosts: localhost
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../../secrets/secret.yml

  tasks:
    - name: trying variables
      debug:
        msg:
          - "{{mysql_name}} and {{nc_url}}"

    - name: testing template file
      template:
        src: ../roles/nextcloud_deploy_docker/templates/docker-compose.yml.j2
        dest: docker-compose.yml

    - name: display docker compose file
      command: cat docker-compose.yml
      register: file_contents_tmp

    - name: Prints the contents of the file
      debug:
        msg: "{{ file_contents_tmp }}"