name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set up Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml

      - name: Run Ansible Playbook
        run: ansible-playbook playbook.yml -vvv
